# Generated by Django 6.1.1 on 2026-09-12 20:20

import django.core.validators
import django.db.models.deletion
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='TBD', max_length=200)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Hard cap on total guests across live bookings.')),
                ('ticket_price_cents', models.PositiveIntegerField(default=500000, help_text='Integer cents. 500000 = 5.000 pesos. Flat price for everyone.')),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('cvu', models.CharField(blank=True, max_length=30)),
                ('account_holder_name', models.CharField(blank=True, help_text="Name the buyer's banking app will show as the destination.", max_length=200)),
                ('organiser_whatsapp', models.CharField(blank=True, help_text='Used for wa.me links on the sold-out and error screens.', max_length=30)),
                ('pending_ttl_minutes', models.PositiveIntegerField(default=45, help_text='How long a pending booking holds its seats.')),
                ('list_deadline', models.DateTimeField(blank=True, help_text='When the name list goes to the venue. Shown to buyers.', null=True)),
                ('sales_close_at', models.DateTimeField(blank=True, help_text='After this, new bookings are refused. Blank means never close.', null=True)),
            ],
            options={
                'verbose_name': 'event settings',
                'verbose_name_plural': 'event settings',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=tickets.models.generate_reference, editable=False, max_length=32, unique=True)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_whatsapp', models.CharField(max_length=30)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('sender_account_name', models.CharField(blank=True, help_text='Name the transfer will arrive under. Often not the buyer -- a partner, a parent, a Mercado Pago handle. Primary key for reconciliation.', max_length=200)),
                ('quantity', models.PositiveSmallIntegerField(help_text='Derived from the guest list; never accepted from the client.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('total_amount', models.PositiveIntegerField(help_text='Integer cents. ticket_price_cents * quantity, nothing added.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('self_confirmed', 'Self-confirmed'), ('verified', 'Verified'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('amount_received_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('verified_source', models.CharField(blank=True, help_text='The statement line that verified this, or "manual". Makes a wrong match reversible.', max_length=500)),
                ('refund_owed_cents', models.PositiveIntegerField(blank=True, help_text='Null means nothing is owed. Refund state is derived from this and refunded_at -- it is deliberately not a status.', null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('list_exported_at', models.DateTimeField(blank=True, help_text='When this booking last appeared on a list sent to the venue.', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='tickets_boo_status_714685_idx')],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='tickets.booking')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
    ]
