# Generated by Django 6.1.1 on 2026-09-15 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_seed_event_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='revolut_currency',
            field=models.CharField(blank=True, help_text='ISO code the Revolut price is in, e.g. EUR.', max_length=3),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='revolut_price_cents',
            field=models.PositiveIntegerField(default=0, help_text='Integer minor units in that currency: 500 = 5.00. Flat for everyone paying via Revolut.'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='revolut_tag',
            field=models.CharField(blank=True, help_text='Revtag without the @. Blank hides Revolut on the pay screen.', max_length=50),
        ),
        migrations.CreateModel(
            name='SongRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_requests', to='tickets.booking')),
            ],
            options={
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('booking', 'position'), name='songrequest_unique_position')],
            },
        ),
    ]
