# Generated by Django 6.1.1 on 2026-09-18 17:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


# The ladder the event is actually selling: 5.000 for the first 50, then 7.000, then
# 9.000 from seat 101. The base price (EventSettings.ticket_price_cents) is the first
# band, so only the two steps are rows.
SEED_TIERS = ((50, 700_000), (100, 900_000))


# The ladder only describes a 130-seat event, so capacity moves with it. An earlier
# draft left capacity alone on the theory that opening 70 more seats should be a
# deliberate admin action -- but price_ladder() only drops a threshold at or PAST
# capacity, so at the old capacity of 60 the 50 threshold is live and the event would
# sell seats 51-60 at 7.000 with no third band and no extra seats. That half-applied
# state is worse than either end state, and nobody asked for it.
SEED_CAPACITY = 130


def seed_price_tiers(apps, schema_editor):
    """Seed the two thresholds, and the capacity the ladder was designed for.

    Only raises capacity, never lowers it: if the organiser has already set something
    larger by hand, this must not quietly take seats away from people holding them.
    """
    EventSettings = apps.get_model('tickets', 'EventSettings')
    PriceTier = apps.get_model('tickets', 'PriceTier')

    for starts_after_seats, price_cents in SEED_TIERS:
        PriceTier.objects.get_or_create(
            starts_after_seats=starts_after_seats,
            defaults={'event_id': 1, 'price_cents': price_cents},
        )

    EventSettings.objects.filter(pk=1, capacity__lt=SEED_CAPACITY).update(
        capacity=SEED_CAPACITY
    )


def drop_price_tiers(apps, schema_editor):
    """Deliberately a no-op.

    Reversing this migration drops the PriceTier table and the Booking columns anyway,
    so deleting rows first buys nothing -- and a targeted delete would remove an
    organiser's own tier at threshold 50 that this migration never created.

    Reversing is destructive regardless: every frozen price_breakdown and
    revolut_amount_cents goes with the columns, and those are the record of what each
    buyer was actually quoted. Capacity is left where it is, for the same reason the
    forward step never lowers it.
    """


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_revolut_and_song_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_breakdown',
            field=models.JSONField(blank=True, default=list, help_text='The quote, per tier band: seats, unit price, how many. A party that straddles a boundary has more than one line. Read-only evidence of what the buyer was shown.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='revolut_amount_cents',
            field=models.PositiveIntegerField(blank=True, help_text='The Revolut figure quoted at the same moment, in minor units. Null for bookings made before Revolut was priced.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.PositiveIntegerField(help_text='Integer cents. The sum of the tier prices for the seats this booking was quoted, nothing added. Frozen at creation.'),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='ticket_price_cents',
            field=models.PositiveIntegerField(default=500000, help_text='Integer cents. 500000 = 5.000 pesos. The price of the FIRST tier -- what a ticket costs until the first PriceTier threshold is passed. With no tiers configured this is a flat price for everyone.'),
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_after_seats', models.PositiveIntegerField(help_text='This price applies from the NEXT seat on. 50 means seats 51 and up.', unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_cents', models.PositiveIntegerField(help_text='Integer cents. 700000 = 7.000 pesos.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='tickets.eventsettings')),
            ],
            options={
                'verbose_name': 'price tier',
                'verbose_name_plural': 'price tiers',
                'ordering': ('starts_after_seats',),
            },
        ),
        migrations.RunPython(seed_price_tiers, drop_price_tiers),
    ]
