# Generated by Django 6.1.1 on 2026-09-18 17:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


# The ladder the event is actually selling: 5.000 for the first 50, then 7.000, then
# 9.000 from seat 101. The base price (EventSettings.ticket_price_cents) is the first
# band, so only the two steps are rows.
SEED_TIERS = ((50, 700_000), (100, 900_000))


def seed_price_tiers(apps, schema_editor):
    """Seed the two thresholds.

    Capacity is deliberately NOT set here. Raising it is what opens 70 more seats for
    sale, and that is the organiser's call from the admin, not something a deploy should
    do on its own. Until capacity goes up these rows are inert -- price_ladder() drops
    any threshold at or past capacity.
    """
    PriceTier = apps.get_model('tickets', 'PriceTier')
    for starts_after_seats, price_cents in SEED_TIERS:
        PriceTier.objects.get_or_create(
            starts_after_seats=starts_after_seats,
            defaults={'event_id': 1, 'price_cents': price_cents},
        )


def drop_price_tiers(apps, schema_editor):
    PriceTier = apps.get_model('tickets', 'PriceTier')
    PriceTier.objects.filter(
        starts_after_seats__in=[seats for seats, _ in SEED_TIERS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_revolut_and_song_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_breakdown',
            field=models.JSONField(blank=True, default=list, help_text='The quote, per tier band: seats, unit price, how many. A party that straddles a boundary has more than one line. Read-only evidence of what the buyer was shown.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='revolut_amount_cents',
            field=models.PositiveIntegerField(blank=True, help_text='The Revolut figure quoted at the same moment, in minor units. Null for bookings made before Revolut was priced.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.PositiveIntegerField(help_text='Integer cents. The sum of the tier prices for the seats this booking was quoted, nothing added. Frozen at creation.'),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='ticket_price_cents',
            field=models.PositiveIntegerField(default=500000, help_text='Integer cents. 500000 = 5.000 pesos. The price of the FIRST tier -- what a ticket costs until the first PriceTier threshold is passed. With no tiers configured this is a flat price for everyone.'),
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_after_seats', models.PositiveIntegerField(help_text='This price applies from the NEXT seat on. 50 means seats 51 and up.', unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_cents', models.PositiveIntegerField(help_text='Integer cents. 700000 = 7.000 pesos.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='tickets.eventsettings')),
            ],
            options={
                'verbose_name': 'price tier',
                'verbose_name_plural': 'price tiers',
                'ordering': ('starts_after_seats',),
            },
        ),
        migrations.RunPython(seed_price_tiers, drop_price_tiers),
    ]
