# Generated by Django 6.1.1 on 2026-09-18 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_price_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsettings',
            name='ticket_price_cents',
            field=models.PositiveIntegerField(default=500000, help_text='Integer cents. 500000 = 5.000 pesos. The price of the FIRST tier -- what a ticket costs until the first PriceTier threshold is passed. With no tiers configured this is a flat price for everyone.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
