# Generated by Django 6.1.1 on 2026-09-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_price_ladder_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='seats_high_water',
            field=models.PositiveIntegerField(default=0, help_text='How far up the price ladder the event has climbed: the most seats ever occupied at once. The ladder reads this, not current occupancy, so the price never falls when a booking lapses or is cancelled -- those seats come back for sale, but at the price the event has reached. Lower it by hand only to deliberately re-open a cheaper band, e.g. after a bulk cancellation.'),
        ),
    ]
