# Generated by Django 6.1.1 on 2026-09-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_seats_high_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='revolut_note',
            field=models.TextField(blank=True, help_text='What payers abroad read, instead of or as well as a fixed figure. Write {total} for this booking\'s peso total or {price} for its per-ticket price and the sentence follows the price ladder without being retyped -- both arrive already formatted (5.000). e.g. "ARS moves daily, so send the equivalent of {total} ARS in USD or GBP and message me once you have."'),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='revolut_currency',
            field=models.CharField(blank=True, help_text='ISO code the Revolut price is in, e.g. EUR. Required only if you set a price below.', max_length=3),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='revolut_price_cents',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Optional. Integer minor units in the currency above: 500 = 5.00, the FIRST-band figure, scaled up for dearer bands. Leave it blank and the note alone is shown -- ARS moves daily, so a pinned figure goes stale within a week.', null=True),
        ),
    ]
