# Generated by Django 6.1.1 on 2026-09-30 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_eventsettings_revolut_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='flat_price_cents',
            field=models.PositiveIntegerField(blank=True, help_text='Integer cents. 700000 = 7.000 pesos. Used only while tiered pricing is off, and required then.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='tiered_pricing',
            field=models.BooleanField(default=True, help_text='Untick to sell every ticket at the flat price below instead of the ladder. The tiers are kept, and come back when this is ticked again.'),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='ticket_price_cents',
            field=models.PositiveIntegerField(default=500000, help_text='Integer cents. 500000 = 5.000 pesos. The price of the FIRST tier -- what a ticket costs until the first PriceTier threshold is passed. With no tiers configured this is a flat price for everyone. Ignored while tiered pricing is switched off.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
